# Generated by Django 5.0.3 on 2024-03-12 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role_auth',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.DO_NOTHING, to='users.role'),
        ),
    ]
