# Generated by Django 5.0.3 on 2024-03-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='description',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servicecompany',
            name='description',
        ),
    ]
