# Generated by Django 5.0.3 on 2024-03-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useraccount_role_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='role_auth',
        ),
    ]
