# Generated by Django 5.0.3 on 2024-03-12 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='car',
            name='serviceCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.car', verbose_name='Машина'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='serviceCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AddField(
            model_name='car',
            name='driveAxleModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.driveaxlemodel', verbose_name='Модель ведущего моста'),
        ),
        migrations.AddField(
            model_name='car',
            name='engineModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.enginemodel', verbose_name='Модель двигателя'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='failureNode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.failurenode', verbose_name='Узел отказа'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.car', verbose_name='Машина'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='serviceCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='organizationOfMaintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organizationofmaintenance', verbose_name='Организация, проводившая ТО'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='recoveryMethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.recoverymethod', verbose_name='Способ восстановления'),
        ),
        migrations.AddField(
            model_name='car',
            name='steeringAxleModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.steeringaxlemodel', verbose_name='Модель управляемого моста'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmissionModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transmissionmodel', verbose_name='Модель трансмиссии'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='typeOfMaintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.typeofmaintenance', verbose_name='Вид ТО'),
        ),
        migrations.AddField(
            model_name='car',
            name='vehicleModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehiclemodel', verbose_name='Модель техники'),
        ),
    ]
