# Generated by Django 5.0.3 on 2024-03-15 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_enginemodelmanager1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EngineModelManager1',
        ),
    ]
